server:
  port: 8761

spring:
  application:
    name: discovery-service
  security:
    user:
      name: eureka
      password: eurekapassword

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:eurekapassword@localhost:8761/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000

management:
  endpoints:
    web:
      exposure:
        include: health,info