server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/musavvirsidhq/wholeSale.git
          default-label: main
          search-paths: wholesale-config-repo/{application}
          clone-on-start: true
          force-pull: true
          skip-ssl-validation: true
        default-label: main
  security:
    user:
      name: configadmin
      password: configpassword

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env
  endpoint:
    health:
      show-details: always